In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
df = pd.read_csv('data/online_retail_dirty_maestria.csv')

antes que nada voy a buscar si hay filas duplicadas para eliminarlas

In [26]:
duplicates = df[df.duplicated(keep=False)]
display(duplicates.sort_values(by=['InvoiceNo', 'StockCode']).head(10))

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
95,536378,22352,LUNCH BOX WITH CUTLERY RETROSPOT,6.0,2010-12-01 09:37:00,2.55,14688.0,United Kingdom
447652,536378,22352,LUNCH BOX WITH CUTLERY RETROSPOT,6.0,2010-12-01 09:37:00,2.55,14688.0,United Kingdom
100,536378,84519A,TOMATO CHARLIE+LOLA COASTER SET,NaN,01/12/2010 09:37,2.95,14688.0,United Kingdom
445834,536378,84519A,TOMATO CHARLIE+LOLA COASTER SET,NaN,01/12/2010 09:37,2.95,14688.0,United Kingdom
132,536381,15056BL,EDWARDIAN PARASOL BLACK,2.0,2010-12-01 09:41:00,5.95,15311.0,United Kingdom
449849,536381,15056BL,EDWARDIAN PARASOL BLACK,2.0,2010-12-01 09:41:00,5.95,15311.0,United Kingdom
130,536381,21533,RETROSPOT LARGE MILK JUG,1.0,01/12/2010 09:41,4.95,15311.0,United Kingdom
449650,536381,21533,RETROSPOT LARGE MILK JUG,1.0,01/12/2010 09:41,4.95,15311.0,United Kingdom
110,536381,21672,WHITE SPOT RED CERAMIC DRAWER KNOB,6.0,2010-12-01 09:41:00,1.25,15311.0,United Kingdom
450501,536381,21672,WHITE SPOT RED CERAMIC DRAWER KNOB,6.0,2010-12-01 09:41:00,1.25,15311.0,United Kingdom

como el resultado es que si, entonces vamos a dejar 1 de cada una

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,NaN,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

con el df.head pudimos ver las primeras 5 filas y encontramos que la columna quantity tiene datos sin asignar desde el principio, entonces vamos a hacer un df.info para ver mejor todo

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 450030 entries, 0 to 467274
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    450030 non-null  str
 1   StockCode    450030 non-null  str
 2   Description  448751 non-null  str
 3   Quantity     414167 non-null  float64
 4   InvoiceDate  450030 non-null  str
 5   UnitPrice    429408 non-null  str
 6   CustomerID   344204 non-null  str
 7   Country      450029 non-null  str
dtypes: float64(1), str(7)
memory usage: 30.9 MB

con el df.info encontramos mucho mas, lo mas relevante es que vimos que la columna customerid tiene muchos datos nulos entonces la vamos a eliminar porque igual es una columna que no consideramos muy relevante

In [7]:
df = df.drop('CustomerID', axis=1)
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,2010-12-01 08:26:00,2.55,United Kingdom
1,536365,71053,WHITE METAL LANTERN,NaN,2010-12-01 08:26:00,3.39,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2010-12-01 08:26:00,2.75,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,2010-12-01 08:26:00,3.39,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,2010-12-01 08:26:00,3.39,United Kingdom

ahora vamos a limpiar la columna de unitprice, ya que esta como object y no como int o float, para eso buscamos los valores que no son numericos

In [8]:

df[pd.to_numeric(df['UnitPrice'], errors='coerce').isna()]['UnitPrice'].unique()

<StringArray>
[   '£0.85',    '£1.85',    '£2.75',        nan,    '£1.95',     '£2.1',
    '£1.25',    '£4.95',    '£2.55',    '£1.45',
 ...
    '£20.8',  '£233.25',   '£16.65', '£4161.06',     '£0.1',     '£5.4',
     '£0.8',    '£1.97',    '£3.88',     '£nan']
Length: 307, dtype: str

es porq tienen el simbolo "£", entonces lo voy a eliminar.

In [9]:
df['UnitPrice'] = df['UnitPrice'].astype(str).str.replace('£', '', regex=False)

y voy a convertir esa columna en float y luego voy a verificar si hay valores en 0

In [10]:
df['UnitPrice'] = pd.to_numeric(df['UnitPrice'], errors='coerce')

In [11]:
zero_prices = df[df['UnitPrice'] == 0]
print(f"Cantidad de registros con UnitPrice igual a 0: {len(zero_prices)}")
display(zero_prices.head())

Cantidad de registros con UnitPrice igual a 0: 2163

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
1970,536545,21134,NaN,NaN,2010-12-01 14:32:00,0.0,United Kingdom
1971,536546,22145,NaN,1.0,2010-12-01 14:33:00,0.0,United Kingdom
1972,536547,37509,NaN,1.0,2010-12-01 14:33:00,0.0,United Kingdom
1987,536549,85226A,NaN,1.0,2010-12-01 14:34:00,0.0,United Kingdom
1988,536550,85044,NaN,1.0,2010-12-01 14:34:00,0.0,United Kingdom

note que hay nulos en otras filas entonces voy a mirar cuantos hay y en que filas, asi puedo ver mejor y decido si elimino las filas que unitprice este en 0

In [12]:

zero_prices = df[df['UnitPrice'] == 0]
print(f"Análisis de nulos en registros con UnitPrice 0:")
zero_prices.isnull().sum()

Análisis de nulos en registros con UnitPrice 0:

InvoiceNo         0
StockCode         0
Description    1209
Quantity        171
InvoiceDate       0
UnitPrice         0
Country           0
dtype: int64

In [13]:
df = df[df['UnitPrice'] > 0]

Ahora enfoquemonos en la columan quantity que es otra que tiene muchos valores nulos tambien

In [14]:
null_count = df['Quantity'].isnull().sum()
display(df[df['Quantity'].isnull()].head())

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,2010-12-01 08:26:00,2.55,United Kingdom
1,536365,71053,WHITE METAL LANTERN,NaN,2010-12-01 08:26:00,3.39,United Kingdom
20,536367,48187,DOORMAT NEW ENGLAND,NaN,2010-12-01 08:34:00,7.95,United Kingdom
45,536370,POST,POSTAGE,NaN,2010-12-01 08:45:00,18.00,France
71,536375,21871,SAVE THE PLANET MUG,NaN,2010-12-01 09:32:00,1.06,United Kingdom

voy a ver cuales valores son negativos y los convierto en positivos ya que probablemente fue un error de digitacion

In [15]:

negative_quantities = df[df['Quantity'] < 0]
print(f"Cantidad de registros con valores negativos: {len(negative_quantities)}")

Cantidad de registros con valores negativos: 7231

In [16]:
df['Quantity'] = df['Quantity'].abs()

aqui miramos los nulos que coincidian con las variables unitprice y description a ver si tenian correlacion fuerte, pero nos dimos cuenta que no, entonces decidimos borrar las filas de nulos en quantity para no introducir ningun sesgo a los datos en caso de aplicar la media

In [17]:
df[df['Quantity'].isnull()][['UnitPrice', 'Description']].isnull().sum()

UnitPrice      0
Description    0
dtype: int64

In [18]:
df = df.dropna(subset=['Quantity'])
df['Quantity'].isnull().sum()

np.int64(0)

tambien voy a cambiar el tipo de dato de la columna invoicedate

In [19]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors='coerce')

ahora en cuanto a la columna country encontramos que hay datos repetidos pero escritos de distinta manera (los de United Kingdom), entonces vvamos a convertir todos los que corresponden a united kingdom en uno solo

In [20]:
df['Country'].unique()

<StringArray>
[      'United Kingdom',      'United  Kingdom',               'France',
                 'U.K.',                   'UK',       'united kingdom',
            'Australia',          'Netherlands',              'Germany',
               'Norway',                 'EIRE',          'Switzerland',
                'Spain',               'Poland',             'Portugal',
                'Italy',              'Belgium',            'Lithuania',
                'Japan',              'Iceland',      'Channel Islands',
              'Denmark',               'Cyprus',               'Sweden',
              'Austria',               'Israel',              'Finland',
              'Bahrain',               'Greece',            'Hong Kong',
            'Singapore',              'Lebanon', 'United Arab Emirates',
         'Saudi Arabia',       'Czech Republic',               'Canada',
          'Unspecified',               'Brazil',                  'USA',
   'European Community',                'Malta',                  'RSA']
Length: 42, dtype: str

In [21]:
uk_variants = ['United  Kingdom', 'U.K.', 'UK', 'united kingdom']
df['Country'] = df['Country'].replace(uk_variants, 'United Kingdom')
df['Country'].unique()

<StringArray>
[      'United Kingdom',               'France',            'Australia',
          'Netherlands',              'Germany',               'Norway',
                 'EIRE',          'Switzerland',                'Spain',
               'Poland',             'Portugal',                'Italy',
              'Belgium',            'Lithuania',                'Japan',
              'Iceland',      'Channel Islands',              'Denmark',
               'Cyprus',               'Sweden',              'Austria',
               'Israel',              'Finland',              'Bahrain',
               'Greece',            'Hong Kong',            'Singapore',
              'Lebanon', 'United Arab Emirates',         'Saudi Arabia',
       'Czech Republic',               'Canada',          'Unspecified',
               'Brazil',                  'USA',   'European Community',
                'Malta',                  'RSA']
Length: 38, dtype: str

In [22]:
print(f"Number of 'Unspecified' values in 'Country' column: {df[df['Country'] == 'Unspecified'].shape[0]}")

Number of 'Unspecified' values in 'Country' column: 354

In [23]:
import plotly.express as px

# Agrupamos por país para el mapa
country_map_data = df.groupby('Country')['Quantity'].sum().reset_index()

# Creamos el mapa interactivo
fig = px.choropleth(country_map_data,
                    locations='Country',
                    locationmode='country names',
                    color='Quantity',
                    hover_name='Country',
                    title='Ventas Globales por País (Mapa Interactivo)',
                    color_continuous_scale=px.colors.sequential.Plasma)

fig.show()

ModuleNotFoundError: No module named 'plotly'